# Generated by Django 4.2.7 on 2023-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyflexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyflex_memebers',
            name='Gender',
            field=models.CharField(default='unknown', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bodyflex_memebers',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bodyflex_memebers',
            name='email',
            field=models.EmailField(default='unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bodyflex_memebers',
            name='firstname',
            field=models.CharField(default='unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bodyflex_memebers',
            name='lastname',
            field=models.CharField(default='unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bodyflex_memebers',
            name='contact',
            field=models.IntegerField(default='unknown', null=True),
        ),
    ]
